#cloud-config
chpasswd:
  expire: false
  list: |
    root:${tmos_admin_password}
    admin:${tmos_admin_password}
tmos_dhcpv4_tmm:
  enabled: true
  rd_enabled: false
  configsync_interface: 1.0
  default_route_interface: 1.0
  inject_routes: true
  icontrollx_trusted_sources: false
  do_enabled: true
  do_declaration:
    schemaVersion: 1.0.0
    class: Device
    async: true
    label: Cloudinit Onboarding
    Common:
      class: Tenant
      provisioningLevels:
        class: Provision
        ltm: nominal
      byoLicense:
        class: License
        licenseType: regKey
        regKey: ${tmos_license_basekey}
  phone_home_url: ${phone_home_url}
  phone_home_url_verify_tls: false
